# SwiftLint configuration for Touch Grass

# Paths to include
included:
  - TouchGrassApp.swift
  - Views
  - Managers
  - Models

# Paths to exclude
excluded:
  - build
  - .build
  - DerivedData
  - TouchGrass.xcodeproj

# Rules
disabled_rules:
  - trailing_whitespace # Often conflicts with Xcode
  - todo # We want to allow TODO comments
  
opt_in_rules:
  - empty_count
  - empty_string
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_xctest_method
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true
  
file_length:
  warning: 500
  error: 1000
  
type_body_length:
  warning: 300
  error: 500
  
function_body_length:
  warning: 50
  error: 100
  
cyclomatic_complexity:
  warning: 10
  error: 20
  
nesting:
  type_level: 2
  function_level: 3
  
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    
large_tuple:
  warning: 3
  error: 4
  
vertical_whitespace:
  max_empty_lines: 2