name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Run Tests
      run: make test
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          build/Logs/Test/*.xcresult
          TouchGrassTests/*.log
    
  lint:
    name: Lint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: make lint || true  # Don't fail on lint for now
    
  build:
    name: Build
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Create Local.xcconfig
      run: |
        cat > Local.xcconfig << EOF
        DEVELOPMENT_TEAM = 
        PRODUCT_BUNDLE_IDENTIFIER = com.touchgrass.ci
        CODE_SIGN_STYLE = Manual
        CODE_SIGN_IDENTITY = 
        EOF
    
    - name: Build App
      run: |
        xcodebuild -project TouchGrass.xcodeproj \
          -scheme TouchGrass \
          -configuration Release \
          -xcconfig Local.xcconfig \
          build \
          SYMROOT=build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/Release/*.app