name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Build app
      run: |
        xcodebuild -project TouchGrass.xcodeproj \
                   -scheme TouchGrass \
                   -configuration Release \
                   build \
                   SYMROOT=build \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   -quiet
    
    - name: Create DMG
      run: |
        DMG_TEMP="dmg-temp"
        mkdir -p "$DMG_TEMP"
        cp -R "build/Release/Touch Grass.app" "$DMG_TEMP/"
        hdiutil create -volname "Touch Grass ${{ steps.get_version.outputs.VERSION }}" \
                       -srcfolder "$DMG_TEMP" \
                       -ov \
                       -format UDZO \
                       "Touch-Grass-v${{ steps.get_version.outputs.VERSION }}.dmg"
        rm -rf "$DMG_TEMP"
    
    - name: Generate checksums
      run: |
        shasum -a 256 "Touch-Grass-v${{ steps.get_version.outputs.VERSION }}.dmg" > SHA256SUMS.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Touch-Grass-v${{ steps.get_version.outputs.VERSION }}.dmg
          SHA256SUMS.txt
        body: |
          ## Installation
          
          1. Download `Touch-Grass-v${{ steps.get_version.outputs.VERSION }}.dmg`
          2. Open the DMG file
          3. Drag `Touch Grass.app` to the Applications folder
          4. Eject the DMG
          5. Open Touch Grass from your Applications folder (you may need to right-click and select "Open" the first time)
          
          ## Requirements
          - macOS 11.0 or later
          
          ## Features
          - Customizable break reminders
          - Calendar awareness for meeting schedules
          - Water tracking
          - Exercise suggestions
          - Work hours configuration
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}